CC  = gcc
CXX = g++

INCLUDES = 
CFLAGS   = -g -Wall $(INCLUDES)
CXXFLAGS = -g -Wall $(INCLUDES)

LDFLAGS = 
LDLIBS = 

.PHONY: default
default: example1 example2





.PHONY: clean
clean:
	rm -f *.o *~ a.out core main example1 example2

.PHONY: all
all: clean default
