CC = gcc
CFLAGS = -g -Wall
LDFLAGS = -g

fileio: fileio.o

.PHONY: all
all: clean fileio

.PHONY: clean
clean:
	rm -f *.o fileio test test1_case1 test1_case2 test2_case1 test2_case2 test3_fwrite test3_fputs

