CC  = gcc
CXX = g++

INCLUDES = 
CFLAGS   = -g -Wall $(INCLUDES)
CXXFLAGS = -g -Wall $(INCLUDES)

LDFLAGS = 
LDLIBS = 

.PHONY: default
default: bitshift

.PHONY: clean
clean:
	rm -f *.o *~ a.out core main bitshift

.PHONY: all
all: clean default

